### ISSUE TITLE
firm_sim_producers assigns a monetary value to producers OutputCapacityTons?

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/afreight#13]
lines 27-33 of firm_sim_producers:
seems to be assigning a monetary value to producers OutputCapacityTons 
```
producers[!is.na(ValEmp),ProdVal:=ValEmp*Emp]
producers[unitcost,UnitCost:=i.UnitCost,on="SCTG"]
producers[,ProdCap:=ProdVal*1E6/UnitCost]

setnames(producers,c("BusID",   "NAICS6_Make","UnitCost",            "ProdCap",           "Emp"),
                   c("SellerID","NAICS",      "NonTransportUnitCost","OutputCapacityTons","Size"))
```

Is this the correct calculation?

**Comment by toliwaga** [comment]
Oh - it is dividing by unit_cost so maybe it is ok?

from InputOutputValues:
ValEmp = ProVal / Emp

OutputCapacityTons = (ValEmp*Emp)  * 100000.0 / UnitCost

what are the units of ProVal?

**Comment by goreaditya** [comment]
The units of ProVal is in Millions of Dollars.
