### ISSUE TITLE
firm_sim_naics_set.R producers count wrong?

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/afreight#15]
firm_sim_naics_set.R has:

```
firms_sum[["producers"]] <- nrow(producers)
...
firms_sum[["consumers"]] <- length(unique(consumers$BuyerID))
```

This suggests that the code things there is one row per producer in producers table, but actually each producer firms appears once for every commodity that uses produced commodity as an input.

Is there a data dictionary somewhere that documents the key data structures (both internal and outputs)? If not, maybe we need one? 

I know that often this kind of documentation is produced after the fact, but I think they are really useful *during* development to ensure that everybody is on the same page...

**Comment by goreaditya** [comment]
The calculations above are correct.
We assume that a producer produces only one commodity and hence there should be one row per producer in the producers table.
We also assume that a consumer can consume number of different commodities so we have some repetition of consumers based on the number of different commodities they consume.
