### ISSUE TITLE
firm_sim_producers.R CumPctProVal computation is wrong

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/afreight#17]
Trying to select only the most top 80% of consumption inputs

```
  setkey(InputOutputValues, NAICS6_Make, ProVal)
  
  # Calculate cumulative pct value of the consumption inputs
  InputOutputValues[, CumPctProVal := cumsum(ProVal)/sum(ProVal), by = NAICS6_Use]

  # Select suppliers including the first above the threshold value
  InputOutputValues <- InputOutputValues[CumPctProVal > 1 - BASE_PROVALTHRESHOLD]
```

Need to sort by (NAICS6_Use, ProVal) so groupby NAICS6_Use members are ordered by ProVal?

I can't validate my results for this step since the R data I have was produced by the old code.

**Comment by toliwaga** [comment]
Or should the cumsum be grouping by NAICS6_Make?

**Comment by goreaditya** [comment]
The `setkey` should be by `(NAICS6_Use, ProVal)`. The `cumsum` grouping should be by `NAICS6_Use` and this has been corrected in the R script now.

**Comment by bstabler** [comment]
To be clear, the python code in this repository is correct and has always been correct, so this issue does not apply to this repository.
