### ISSUE TITLE
International TAZ firms esizecat and emp values wrong?

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/afreight#8]
firm_sim_scale_employees_taz drops firms with zero employees. 

In the existing FirmsandEstablishments.csv, International (TAZ==0) firms all have esizecat ‘e12’ and emp 0 so they are all dropped.

**Comment by goreaditya** [comment]
This issue has been resolved in the R script. The new output will contain `emp` value of 5000 (mean employment) for `e12` size category and a value of 2 (mean employment) for `e1` size category.
